//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wodeyun.Bf.Execute.Wrappers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wodeyun.Bf.Execute.Wrappers.Executor")]
    public interface Executor
    {
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Executor/Execute", ReplyAction="http://tempuri.org/Executor/ExecuteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wodeyun.Gf.Entities.Entity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wodeyun.Gf.Entities.Entity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wodeyun.Gf.Entities.EntityCollection))]
        object Execute(string service, string method, object[] args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecutorChannel : Wodeyun.Bf.Execute.Wrappers.Executor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutorClient : System.ServiceModel.ClientBase<Wodeyun.Bf.Execute.Wrappers.Executor>, Wodeyun.Bf.Execute.Wrappers.Executor
    {
        
        public ExecutorClient()
        {
        }
        
        public ExecutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ExecutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ExecutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ExecutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public object Execute(string service, string method, object[] args)
        {
            return base.Channel.Execute(service, method, args);
        }
    }
}
