//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wodeyun.Bf.Token.Wrappers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wodeyun.Bf.Token.Wrappers.TokenService")]
    public interface TokenService
    {
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenService/GetTokenByLinkAndUsernameAndPassword", ReplyAction="http://tempuri.org/TokenService/GetTokenByLinkAndUsernameAndPasswordResponse")]
        Wodeyun.Gf.Entities.Entity GetTokenByLinkAndUsernameAndPassword(int link, string username, string password);
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenService/CheckToken", ReplyAction="http://tempuri.org/TokenService/CheckTokenResponse")]
        Wodeyun.Gf.Entities.Entity CheckToken(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TokenServiceChannel : Wodeyun.Bf.Token.Wrappers.TokenService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServiceClient : System.ServiceModel.ClientBase<Wodeyun.Bf.Token.Wrappers.TokenService>, Wodeyun.Bf.Token.Wrappers.TokenService
    {
        
        public TokenServiceClient()
        {
        }
        
        public TokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Wodeyun.Gf.Entities.Entity GetTokenByLinkAndUsernameAndPassword(int link, string username, string password)
        {
            return base.Channel.GetTokenByLinkAndUsernameAndPassword(link, username, password);
        }
        
        public Wodeyun.Gf.Entities.Entity CheckToken(string token)
        {
            return base.Channel.CheckToken(token);
        }
    }
}
