//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wodeyun.Bf.Exchange.Wrappers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wodeyun.Bf.Exchange.Wrappers.MultiService")]
    public interface MultiService
    {
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiService/Start", ReplyAction="http://tempuri.org/MultiService/StartResponse")]
        Wodeyun.Gf.Entities.Entity Start(string uniques, Wodeyun.Gf.Entities.Entity entity);
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiService/Finish", ReplyAction="http://tempuri.org/MultiService/FinishResponse")]
        Wodeyun.Gf.Entities.Entity Finish(string uniques, Wodeyun.Gf.Entities.Entity entity);
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiService/Upload", ReplyAction="http://tempuri.org/MultiService/UploadResponse")]
        void Upload(string unique, Wodeyun.Gf.Entities.Entity entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MultiServiceChannel : Wodeyun.Bf.Exchange.Wrappers.MultiService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiServiceClient : System.ServiceModel.ClientBase<Wodeyun.Bf.Exchange.Wrappers.MultiService>, Wodeyun.Bf.Exchange.Wrappers.MultiService
    {
        
        public MultiServiceClient()
        {
        }
        
        public MultiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MultiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MultiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MultiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Wodeyun.Gf.Entities.Entity Start(string uniques, Wodeyun.Gf.Entities.Entity entity)
        {
            return base.Channel.Start(uniques, entity);
        }
        
        public Wodeyun.Gf.Entities.Entity Finish(string uniques, Wodeyun.Gf.Entities.Entity entity)
        {
            return base.Channel.Finish(uniques, entity);
        }
        
        public void Upload(string unique, Wodeyun.Gf.Entities.Entity entity)
        {
            base.Channel.Upload(unique, entity);
        }
    }
}
