//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wodeyun.Bf.Exchange.Wrappers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wodeyun.Bf.Exchange.Wrappers.SingleService")]
    public interface SingleService
    {
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleService/Execute", ReplyAction="http://tempuri.org/SingleService/ExecuteResponse")]
        Wodeyun.Gf.Entities.Entity Execute(string uniques, Wodeyun.Gf.Entities.Entity entity, int second);
        
        [System.ServiceModel.Web.WebInvoke(BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleService/Update", ReplyAction="http://tempuri.org/SingleService/UpdateResponse")]
        void Update(string unique, Wodeyun.Gf.Entities.Entity entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SingleServiceChannel : Wodeyun.Bf.Exchange.Wrappers.SingleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleServiceClient : System.ServiceModel.ClientBase<Wodeyun.Bf.Exchange.Wrappers.SingleService>, Wodeyun.Bf.Exchange.Wrappers.SingleService
    {
        
        public SingleServiceClient()
        {
        }
        
        public SingleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SingleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SingleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SingleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Wodeyun.Gf.Entities.Entity Execute(string uniques, Wodeyun.Gf.Entities.Entity entity, int second)
        {
            return base.Channel.Execute(uniques, entity, second);
        }
        
        public void Update(string unique, Wodeyun.Gf.Entities.Entity entity)
        {
            base.Channel.Update(unique, entity);
        }
    }
}
